- youtube_id: 'lAihDAJX8Ow'
  artist: 'Mastodon'
  track_name: 'Curl of the Burl'
- youtube_id: '0Xfvk028Kv0'
  artist: 'Trivium'
  track_name: 'In Waves'
- youtube_id: '6uYOEy-WghM'
  artist: 'Opeth'
  track_name: 'Harlequin Forest (Live)'
- youtube_id: '9sTQ0QdkN3Q'
  artist: 'Bullet For My Valentine'
  track_name: "Tears Don't Fall"
- youtube_id: 'IbPuTwo1bxs'
  artist: 'Breaking Benjamin'
  track_name: 'Dear Agony'
- youtube_id: 'xRIVJ7aLHTE'
  artist: 'Gojira'
  track_name: 'Flying Whales (Live)'
- youtube_id: 'BGHlZwMYO9g'
  artist: 'Gojira'
  track_name: "L'Enfant Sauvage"
